bigyouth_embedly_oembed:
    pattern:  /oembed
    defaults: { _controller: IrvyneEmbedlyBundle:Embedly:index }
bigyouth_embedly_oembed_show:
    pattern:  /oembed/{url}
    defaults: { _controller: IrvyneEmbedlyBundle:Embedly:show }
    requirements:
        url: ".+"
