parameters:
    irvyne_embedly.key: ~ # DependencyInjection Configuration
    irvyne_embedly.class: Irvyne\EmbedlyBundle\Service\EmbedlyService

services:
    irvyne.embedly:
        class:     %irvyne_embedly.class%
        arguments: [%irvyne_embedly.key%]