language: php

php:
  - 5.5

env:
  - SYMFONY_VERSION='2.2.*'
  - SYMFONY_VERSION='2.3.*'
  - SYMFONY_VERSION='2.4.*'

before_script:
    - composer require --no-update symfony/framework-bundle=$SYMFONY_VERSION
    - composer require --no-update symfony/security-bundle=$SYMFONY_VERSION
    - composer install --dev --prefer-source